# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "chargify/stoplight-platform-developer-docs"
          source_branch: "main"
          destination_repo: "chargify/developer-docs"
          destination_branch: "main"
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }}
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "chargify/stoplight-platform-developer-docs"
          source_branch: "staging"
          destination_repo: "chargify/developer-docs"
          destination_branch: "staging"
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }}
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
